#define _CRT_SECURE_NO_WARNINGS
#include "Crosy.h"
#include <assert.h>
#include <vector>
#include <stdio.h>
#include <GL/glew.h>
#include <GL/glfw3.h>
#include <glm/glm.hpp>
#include <glm/gtc/matrix_transform.hpp>
#include "3rdParty/SOIL2/SOIL2.h"
