#pragma once

enum SDFF_Error
{
  SDFF_OK = 0,
  SDFF_FONT_ALREADY_EXISTS,
  SDFF_CHAR_ALREADY_EXISTS,
  SDFF_FONT_NOT_EXISTS,
  SDFF_FT_NEW_FACE_ERROR,
  SDFF_FT_SET_CHAR_SIZE_ERROR,
  SDFF_FT_LOAD_CHAR_ERROR,
  SDFF_INVALID_VALUE,
  SDFF_NOT_INITIALIZED
};
